[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"

[rpc_endpoints]
rise_testnet = "https://testnet.riselabs.xyz"

[etherscan]
rise_testnet = { key = "", url = "https://explorer.testnet.riselabs.xyz/api" }
